# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      run: |
        ls
        mkdir anji
        ls
        cd anji
        git clone https://github.com/AnjiB/anji-kot-lin.git
        ls
        cd anji-kot-lin
        ls
